- name: install bika.penelope
  become: yes
  become_user: "{{ BIKA_USER }}"
  git: repo=https://github.com/ratzeni/bika.penelope.git dest=/home/{{ BIKA_USER }}/bika.penelope

- name: copy virtualhost config
  become: yes
  template: src=virtualhost.j2 dest=/etc/apache2/sites-available/bika.conf mode=0644

- name: apache2 listen on port 8081
    lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 80\nListen 8081" state=present
    notify:
      - restart apache2

- name: a2ensite {{ DOMAIN }}
  become: yes
  command: a2ensite {{ DOMAIN }}
  args:
    creates: /etc/apache2/sites-enabled/{{ DOMAIN }}.conf
  notify:
    - restart apache2