- name: install bika.client and dependency
  become: yes
  become_user: "{{ BIKA_USER }}"
  pip: name={{ item }} extra_args='--user' editable=false
  with_items:
    - paste
    - python-daemon
    - lockfile
    - bottle
    - git+https://github.com/ratzeni/bika.client.git

- name: install aroundBika bundle
  become: yes
  become_user: "{{ BIKA_USER }}"
  git: repo={{ item.repo }} dest={{ item.dest }} force=yes
  with_items:
    - { repo: 'https://github.com/ratzeni/bika.penelope.git', dest: "/home/{{ BIKA_USER }}/bika.penelope" }
    - { repo: 'https://github.com/ratzeni/bika.webservice.git', dest: "/home/{{ BIKA_USER }}/bika.webservice" }
    - { repo: 'https://github.com/gmauro/alta.git', dest: "/home/{{ BIKA_USER }}/alta" }

- name: install alta library
  become: yes
  become_user: "{{ BIKA_USER }}"
  command: chdir=/home/{{ BIKA_USER }}/alta  python setup.py install --user

- name: set penelope services mode
  file: path=/home/{{ BIKA_USER }}/bika.webservice/{{ item }} mode=0755
  with_items:
    - penelope_read_service.sh
    - penelope_write_service.sh

- name: rename init.module.js.sample
  command: mv /home/{{ BIKA_USER }}/bika.penelope/app/init.module.js.sample /home/{{ BIKA_USER }}/bika.penelope/app/init.module.js

- name: replace vars into bika.penelope config script
  replace: dest="/home/{{ BIKA_USER }}/bika.penelope/app/init.module.js" regexp="{{ item.regexp }}" replace="{{ item.repl }}"
  with_items:
    - { regexp: "DUMMY_READ_REST_URL", repl: "{{ READ_REST_URL }}" }
    - { regexp: "DUMMY_WRITE_REST_URL", repl: "{{ WRITE_REST_URL }}" }
    - { regexp: "DUMMY_BIKA_HOST", repl: " {{ BIKA_HOST }}" }
    - { regexp: "DUMMY_IRODS_RESOURCE", repl: "{{ IRODS_RESOURCE }}" }
    - { regexp: "DUMMY_IRODS_SAMPLESHEET_COLLECTION", repl: "{{ IRODS_SAMPLESHEET_COLLECTION }}" }
    - { regexp: "DUMMY_IRODS_HOST", repl: "{{ IRODS_HOST }}" }
    - { regexp: "DUMMY_IRODS_USER", repl: "{{ IRODS_USER }}" }
    - { regexp: "DUMMY_IRODS_PASSWORD", repl: "{{ IRODS_PASSWORD }}" }
    - { regexp: "DUMMY_IRODS_ZONE", repl: "{{ IRODS_ZONE }}" }
    - { regexp: "DUMMY_SSH_HOST", repl: "{{ SSH_HOST }}" }
    - { regexp: "DUMMY_SSH_USER", repl: "{{ SSH_USER }}" }
    - { regexp: "DUMMY_TMP_FOLDER", repl: "{{ TMP_FOLDER }}" }
    - { regexp: "DUMMY_RUN_FOLDERS", repl: "{{ RUN_FOLDERS }}" }
    - { regexp: "DUMMY_RUN_INFO_FILE", repl: "{{ RUN_INFO_FILE }}" }
    - { regexp: "DUMMY_RUN_PARAMETERS_FILE", repl: "{{ RUN_PARAMETERS_FILE }}" }


- name: rename init.cfg.sample
  command: mv /home/{{ BIKA_USER }}/bika.webservice/init.cfg.sample /home/{{ BIKA_USER }}/bika.webservice/init.cfg

- name: create bika.webservice dirs
  become: yes
  become_user: "{{ BIKA_USER }}"
  file: path={{ item }} state=directory mode=0755
  with_items:
    - /home/{{ BIKA_USER }}/var/run
    - /home/{{ BIKA_USER }}/var/log

- name: replace vars into bika.webservice config script
  replace: dest="/home/{{ BIKA_USER }}/bika.webservice/init.cfg" regexp="{{ item.regexp }}" replace="{{ item.repl }}"
  with_items:
    - { regexp: "DUMMY_SERVICE_DIR", repl: "$HOME/bika.webservice" }
    - { regexp: "DUMMY_PID_FILE_READ", repl: "$HOME/var/run/bika_service.read.pid" }
    - { regexp: "DUMMY_PID_FILE_WRITE", repl: "$HOME/var/run/bika_service.write.pid" }
    - { regexp: "DUMMY_LOG_FILE_READ", repl: "$HOME/var/log/bika_service.read.log" }
    - { regexp: "DUMMY_LOG_FILE_WRITE", repl: "$HOME/var/log/bika_service.write.log" }
    - { regexp: "DUMMY_HOST", repl: "localhost" }
    - { regexp: "DUMMY_PORT_READ", repl: "8088" }
    - { regexp: "DUMMY_PORT_WRITE", repl: "8086" }
    - { regexp: "DUMMY_SERVER_READ", repl: "paste" }
    - { regexp: "DUMMY_SERVER_WRITE", repl: "wsgiref" }

- name: copy virtualhost config
  become: yes
  template: src=virtualhost.j2 dest=/etc/apache2/sites-available/bika.conf mode=0644

- name: apache2 listen on port 8081
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 80\nListen 8081" state=present
  notify:
    - restart apache2

- name: a2ensite {{ DOMAIN }}
  become: yes
  command: a2ensite {{ DOMAIN }}
  args:
    creates: /etc/apache2/sites-enabled/{{ DOMAIN }}.conf
  notify:
    - restart apache2