- name: install bika.client and dependency
  become: yes
  become_user: "{{ BIKA_USER }}"
  pip: name={{ item }} extra_args='--user' editable=false
  with_items:
    - Paste
    - git+https://github.com/ratzeni/bika.client.git

- name: install aroundBika bundle
  become: yes
  become_user: "{{ BIKA_USER }}"
  git: repo={{ item.repo }} dest={{ item.dest }}
  with_items:
    - { repo: 'https://github.com/ratzeni/bika.penelope.git', dest: "/home/{{ BIKA_USER }}/bika.penelope" }
    - { repo: 'https://github.com/ratzeni/bika.webservice.git', dest: "/home/{{ BIKA_USER }}/bika.webservice" }

- name: set penelope services mode
  file: path=/home/{{ BIKA_USER }}/bika.webservice/{{ item }} mode=0755
  with_items:
    - penelope_read_service.sh
    - penelope_write_service.sh

- name: rename init.cfg.sample
  command: mv /home/{{ BIKA_USER }}/bika.webservice/init.cfg.sample /home/{{ BIKA_USER }}/bika.webservice/init.cfg

- name: replace vars into bika.webservice config script
  replace: dest="/home/{{ BIKA_USER }}/bika.webservice/init.cfg" regexp="{{ item.regexp }}" replace="{{ item.repl }}"
  with_items:
    - { regexp: "DUMMY_SERVICE_DIR", repl: "$HOME/bika.webservice" }
    - { regexp: "DUMMY_PID_FILE_READ", repl: "$HOME/var/run/bika_service.read.pid" }
    - { regexp: "DUMMY_PID_FILE_WRITE", repl: "$HOME/var/run/bika_service.write.pid" }
    - { regexp: "DUMMY_LOG_FILE_READ", repl: "$HOME/var/log/bika_service.read.log" }
    - { regexp: "DUMMY_LOG_FILE_WRITE", repl: "$HOME/var/log/bika_service.write.log" }
    - { regexp: "DUMMY_HOST", repl: "bikaplone" }
    - { regexp: "DUMMY_PORT_READ", repl: "8088" }
    - { regexp: "DUMMY_PORT_WRITE", repl: "8086" }
    - { regexp: "DUMMY_SERVER_READ", repl: "paste" }
    - { regexp: "DUMMY_SERVER_WRITE", repl: "wsgiref" }

- name: copy virtualhost config
  become: yes
  template: src=virtualhost.j2 dest=/etc/apache2/sites-available/bika.conf mode=0644

- name: apache2 listen on port 8081
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 80\nListen 8081" state=present
  notify:
    - restart apache2

- name: a2ensite {{ DOMAIN }}
  become: yes
  command: a2ensite {{ DOMAIN }}
  args:
    creates: /etc/apache2/sites-enabled/{{ DOMAIN }}.conf
  notify:
    - restart apache2