- name: install packages needed by bika.penelope and bika.webservice
  become: yes
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - apache2
    - git
    - supervisor
    - vim
    - python-paste
  when: ansible_os_family == "Debian"